server:
    port: 8800
spring:
    security:
        user:
            name: user
            password: 123456
    application:
        name: sc-config-server
    cloud:
        config:
            server:
                git:
#                    uri: https://github.com/Wang-Jun-Chao/spring-cloud-config
#                    search-paths: sc-provider
                    uri: https://github.com/zhong2peng/spring-cloud-config-repository
            label: master

eureka:
    client:
        service-url:
            defaultZone: http://user:123456@localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        appname: ${spring.application.name}