server:
  port: 8200
spring:
  application:
    name: sc-consumer-feign
  cloud:
    config:
      discovery:
        enabled: true
        service-id: sc-config-server
      fail-fast: true
      username: user
      password: 123456
      profile: test
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0


# 新版配置，否则后面dashboard无法找到hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}