server:
  port: 8080
spring:
  application:
    name: sc-provider
  cloud:
    config:
      discovery:
        enabled: true
        service-id: sc-config-server
      fail-fast: true
      username: user
      password: 123456
      profile: test
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}