server:
  port: 8011
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    enabled: false
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
