server:
  port: 8000
spring:
  application:
    name: consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
feign:
  client:
    config:
      provider-user-feign:
        loggerLevel: full